// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJCeOSI7_K6yasAhWXQ2ZKMz5Jq2H5WtM',
    appId: '1:755991867844:web:24089d90989379b7b63491',
    messagingSenderId: '755991867844',
    projectId: 'location-app-project-ce854',
    authDomain: 'location-app-project-ce854.firebaseapp.com',
    databaseURL: 'https://location-app-project-ce854-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'location-app-project-ce854.firebasestorage.app',
    measurementId: 'G-LR2V8EJWN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJs_be_jGwIlzGOGddNtJJxRgKcbUNEmA',
    appId: '1:755991867844:android:1fca381aec1e4c82b63491',
    messagingSenderId: '755991867844',
    projectId: 'location-app-project-ce854',
    databaseURL: 'https://location-app-project-ce854-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'location-app-project-ce854.firebasestorage.app',
  );
}